### ISSUE TITLE
Add Book via ISBN doesn`t work 

### ISSUE THREAD

**Issue by Sabokou** [BennerLukas/biblio#40]
Tested using ISBN-11: 3662589753

**Comment by Sabokou** [comment]
Könnte dran liegen, dass nur ISBN-13 supported ist. Hinweis evtl. hinzufügen.

**Comment by BennerLukas** [comment]
978-0062893338 this works


this does not  978-0545162074

**Comment by BennerLukas** [comment]
es gehen auch andere ISBN13 nicht

**Comment by Sabokou** [comment]
![image](https://user-images.githubusercontent.com/52411026/113619428-3f1c3100-9659-11eb-8cb4-8263b3959618.png)
Evtl. sollten wir einfach von goog (ist standard) wechseln oder einfach alles 3 durchprüfen nach dem Motto:
--> default | if output = {} --> wiki  | if output = {} --> openl | if output = {} --> fail
